### ISSUE TITLE
uniformize ui behaviour for flipping between seqs

### ISSUE THREAD

**Issue by pariasm** [kidanger/VideoProcessingViewer#7]
There are two types of researches in image processing. The ones that flip images to compare the results and the bad researchers. Good researchers will find the vpv flipping experience confusing.

If I launch vpv with 
`$ vpv aw seq1 seq2`
Then I can switch between layouts and I can flip between sequenceswith either `tab`/`shift+tab` or the number keys (in the fullscreen layout). **But** if I launch vpv as
`$ vpv seq1 seq2`
then I can flip with `space` and `backspace`, but I can't switch to other layouts. This isn't right. The same behaviour should be attained with the same keys always.

I know that the reason for this is the distinction between windows and sequences: a single window can have different seqs. But this hierarchy should be transparent for the basic user (_homo magdeburgensis_)  and be accessible only for an expert user with a specific need.

I'd like to suggest the following:

1. By **default** vpv should launch in `aw` mode (each input seq is opened in a separate window).
2. It should be possible for the user to choose the the initial layout (how the windows are shown when the program starts) from the command line. For example `$ vpv fs seq1\* seq2\* seq3\*` for fullscreen mode. Or `$ vpv hs s1\* s2\*` for a horizontal split. Or etcetera.
3. In full-screen layout I'd allow the user to flip seqs using `space` and `backspace`, to honour pvflip (in addition to the numbers, which are also very useful to flip between sequences that are not adjacent).

**Comment by kidanger** [comment]
Thanks for the ideas.
1. fixed by 836cae4
2. fixed by 6923872
3. wontfix for now
